DNUM-SocialGouv/eclaire

config/users.yaml, nest-cli.json, package.json, src/app.controller.ts, src/app.module.ts, src/app.service.ts, src/auth/auth.module.ts, src/auth/auth.service.spec.ts, src/auth/auth.service.ts, src/auth/jwt-auth.guard.ts, src/auth/jwt.strategy.ts, src/auth/local-auth-guard.ts, src/auth/local.strategy.ts, src/auth/public.decorator.ts, src/auth/role.enum.ts, src/auth/roles.decorator.ts, src/interfaces/user.interface.ts, src/main.ts, src/users/user.ts, src/users/users.module.ts, src/users/users.service.spec.ts, src/users/users.service.ts, yarn.lock
Ajout d'une authentification JWT
=> ECLAIRE: feat(Auth) Ajout de l'authentification JWT

src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/ClinicalTrial.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/ClinicalTrialModel.ts
=> ECL-06 feat(clinical trial) last revision date

src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/ClinicalTrial.ts, src/clinical-trial/application/entities/StudyType.ts, src/clinical-trial/application/entities/Title.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/model/ClinicalTrialModel.ts, src/clinical-trial/gateways/model/StudyTypeModel.ts, src/clinical-trial/gateways/model/TitleModel.ts, stryker.conf.json
=> ECL refact(clinical trial) sur les entities et tests

src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/ClinicalTrial.ts, src/clinical-trial/application/entities/Recruitment.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/ClinicalTrialModel.ts
=> ECL-07: feat(Clinical Trial) Add utn and secondary ids

src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/Recruitment.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/RecruitmentModel.ts
=> ECL-11 feat(clinical trial) recruitment target number

src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/ClinicalTrial.ts, src/clinical-trial/application/entities/Contact.test.ts, src/clinical-trial/application/entities/Contact.ts, src/clinical-trial/application/entities/ContactDetails.test.ts, src/clinical-trial/application/entities/ContactDetails.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/ClinicalTrialModel.ts, src/clinical-trial/gateways/model/ContactDetailsModel.ts, src/clinical-trial/gateways/model/ContactModel.ts
=> ECL-13: feat(Clinical Trial) Add Contact informations (public and scientific)

src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/ClinicalTrial.ts, src/clinical-trial/application/entities/TherapeuticArea.test.ts, src/clinical-trial/application/entities/TherapeuticArea.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/ClinicalTrialModel.ts, src/clinical-trial/gateways/model/TherapeuticAreaModel.ts
=> (WIP) ECL-03: feat(Clinical Trial) Add medical conditions and MedDRA informations

src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/ClinicalTrial.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/ClinicalTrialModel.ts
=> ECL-12 feat(clinical trial) primary sponsor

src/clinical-trial/gateways/file-repository/clinical-trials.json
Mise à jours du fichier de file DB pour tests Postman
=> update(File Repository) Update CTs (Clinical Trials) values

src/auth/auth.controller.ts, src/auth/auth.service.ts, src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/ClinicalTrial.ts, src/clinical-trial/application/entities/Contact.test.ts, src/clinical-trial/application/entities/ContactDetails.test.ts, src/clinical-trial/application/entities/TherapeuticArea.test.ts, src/clinical-trial/controllers/get-one-clinical-trial.controller.ts, src/clinical-trial/gateways/file-repository/clinical-trial-factory.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/ClinicalTrialModel.ts, src/swagger/swagger.service.ts, src/users/User.ts, src/users/user.controller.ts, src/users/users.service.test.ts, src/users/users.service.ts
=> ECL-16 feat(clinical trial) summary clinical trial

src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/Criteria.test.ts, src/clinical-trial/application/entities/Criteria.ts, src/clinical-trial/application/entities/Recruitment.test.ts, src/clinical-trial/application/entities/Recruitment.ts, src/clinical-trial/controllers/get-one-clinical-trial.controller.ts, src/clinical-trial/gateways/file-repository/clinical-trial-factory.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/CriteriaModel.ts, src/clinical-trial/gateways/model/RecruitmentModel.ts
=> ECL-15 feat(clinical trial) exclusion and inclusion criteria

src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/ClinicalTrial.ts, src/clinical-trial/application/entities/StudyType.test.ts, src/clinical-trial/application/entities/Title.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-factory.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/ClinicalTrialModel.ts
=> ECL-17 feat(clinical trial) clinical_trial_category and clinical_trial_type

package.json, src/clinical-trial/application/Exceptions/NotFoundClinicalTrialException.test.ts, src/clinical-trial/application/Exceptions/NotFoundClinicalTrialException.ts, src/clinical-trial/application/entities/ClinicalTrial.test.ts, src/clinical-trial/application/entities/Contact.test.ts, src/clinical-trial/application/entities/Contact.ts, src/clinical-trial/application/entities/Recruitment.test.ts, src/clinical-trial/application/entities/StudyType.test.ts, src/clinical-trial/application/entities/StudyType.ts, src/clinical-trial/controllers/get-one-clinical-trial.controller.ts, src/clinical-trial/gateways/clinical-trial-factory.test.ts, src/clinical-trial/gateways/clinical-trial-factory.ts, src/clinical-trial/gateways/clinical-trial-model-testing-factory.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.test.ts, src/clinical-trial/gateways/file-repository/clinical-trial-file.repository.ts, src/clinical-trial/gateways/file-repository/clinical-trials.json, src/clinical-trial/gateways/model/ContactModel.ts, stryker.conf.json, test/app.e2e-test.ts, test/jest-e2e.json
=> ECL refact(clinical trial) end to end

src/api/clinical-trial/application/entities/ClinicalTrial.ts, src/api/clinical-trial/application/entities/Criteria.ts, src/api/clinical-trial/application/entities/Recruitment.ts, src/api/clinical-trial/application/entities/TherapeuticArea.ts, src/api/clinical-trial/application/entities/Title.ts, src/etl/traductions/RecruitmentStatus.ts
=> ECL-36 feat(clinical trial) update documentation

src/etl/ClinicalTrialModelFactory.ts, src/etl/EtlService.test.ts, src/etl/dto/RiphDmDto.ts, src/etl/dto/RiphJardeDto.ts, src/shared/test/helpers/elasticsearchHelper.ts
=> ECL-29 feat(etl) update last revision date

.github/pull_request_template.md, src/etl/ClinicalTrialModelFactory.test.ts, src/etl/ClinicalTrialModelFactory.ts, src/etl/EtlModule.ts, src/etl/clinicalTrialIndexMapping.ts, src/shared/test/helpers/elasticsearchHelper.ts, yarn.lock
=> ECL feat(ETL) update from extract v4

nest-cli.json, package.json, src/AppModule.ts, src/etl/EtlShard.ts, src/etl/EtlShardCtis.ts, src/etl/EtlShardDm.ts, src/etl/EtlShardJarde.ts, src/etl/FhirEtlModule.ts, src/etl/FhirEtlService.ts, src/etl/console.ts, src/shared/elasticsearch/ElasticsearchService.test.ts, src/shared/elasticsearch/ElasticsearchService.ts, src/shared/test/helpers/fakeHelper.ts
=> [TECH] feat: add delete elastic index in console and use dynamic import

src/etl/RiphCtisResearchStudyModelFactory.test.ts, src/etl/RiphDmResearchStudyModelFactory.test.ts, src/etl/RiphJardeResearchStudyModelFactory.test.ts, src/shared/models/fhir/SpecialPurposeDataType/MetaModel.test.ts, src/shared/models/fhir/SpecialPurposeDataType/MetaModel.ts
=> ECL fix the last updated date within ETL

src/etl/RiphDmResearchStudyModelFactory.test.ts, src/etl/RiphDmResearchStudyModelFactory.ts, src/etl/RiphJardeResearchStudyModelFactory.test.ts, src/etl/RiphJardeResearchStudyModelFactory.ts
=> fix: add missing ids in JARDE and DM

src/api/clinical-trial/gateways/es-repository/EsClinicalTrialRepository.ts, src/api/research-study/application/contracts/ResearchStudyRepository.ts, src/api/research-study/application/entities/BundleModel.ts, src/api/research-study/application/entities/ElasticsearchBody.ts, src/api/research-study/controllers/ResearchStudyQueryModel.ts, src/api/research-study/controllers/converter/researchStudyQueryToElasticsearchQuery.test.ts, src/api/research-study/controllers/converter/researchStudyQueryToElasticsearchQuery.ts, src/api/research-study/gateways/EsResearchStudyRepository.test.ts, src/api/research-study/gateways/EsResearchStudyRepository.ts, src/etl/FhirEtlModule.ts, src/shared/elasticsearch/ElasticsearchService.test.ts, src/shared/elasticsearch/ElasticsearchService.ts, stryker-api.conf.json, vitest.config.ts
=> ECL update search pagination when above 10K results

package.json, src/etl/ClinicalTrialModelFactory.test.ts, src/etl/EtlService.test.ts, src/etl/EtlShardJarde.test.ts, src/etl/FhirEtlModule.ts, src/etl/FhirEtlService.test.ts, src/etl/FhirEtlService.ts, src/etl/RiphJardeResearchStudyModelFactory.test.ts, src/etl/console.ts, src/shared/test/helpers/elasticsearchHelper.ts
=> refactor: import jarde with one file

src/api/research-study/application/entities/ElasticsearchBody.ts, src/api/research-study/controllers/converter/researchStudyQueryToElasticsearchQuery.ts
=> ECL refacto research study query to Elasticsearch query implementation

src/etl/factories/RiphCtisResearchStudyModelFactory.ts, src/shared/models/eclaire/ModelUtils.ts
=> ECL rename ReaderService -> FileReaderService

src/etl/factories/RiphCtisResearchStudyModelFactory.ts, src/etl/factories/RiphDmResearchStudyModelFactory.ts, src/etl/factories/RiphJardeResearchStudyModelFactory.ts
=> ECL refactor primary and secondary sponsor within factories

src/shared/models/data-types/CodingModel.test.ts, src/shared/models/data-types/RangeModel.test.ts, src/shared/models/domain-resources/OrganizationModel.test.ts
=> ECL refacto model tests

src/etl/dto/EclaireDto.ts, src/etl/dto/RiphCtisDto.ts, src/etl/dto/RiphDmDto.ts, src/etl/dto/RiphJardeDto.ts, src/shared/models/backbone-elements/GroupCharacteristicModel.ts, src/shared/models/backbone-elements/OrganizationContactModel.ts, src/shared/models/data-types/AddressModel.ts, src/shared/models/data-types/CodeableConceptModel.ts, src/shared/models/data-types/CodingModel.ts, src/shared/models/data-types/ContactPointModel.ts, src/shared/models/data-types/HumanNameModel.ts, src/shared/models/data-types/IdentifierModel.ts, src/shared/models/data-types/PeriodModel.ts, src/shared/models/data-types/QuantityModel.ts, src/shared/models/data-types/RangeModel.ts, src/shared/models/domain-resources/GroupModel.ts, src/shared/models/domain-resources/LocationModel.ts, src/shared/models/domain-resources/OrganizationModel.ts, src/shared/models/eclaire/ReferenceContentsModel.ts, src/shared/models/metadata-types/ContactDetailModel.ts, src/shared/models/special-purpose-data-types/ExtensionModel.ts, src/shared/models/special-purpose-data-types/MetaModel.ts, src/shared/models/special-purpose-data-types/ReferenceModel.ts
=> ECL add private to the constructor with static method

src/api/e2e.test.ts, src/api/research-study/gateways/EsResearchStudyRepository.test.ts, src/etl/ingest-pipelines/IngestPipeline.ts, src/etl/ingest-pipelines/IngestPipelineCtis.test.ts, src/etl/ingest-pipelines/IngestPipelineCtis.ts, src/etl/ingest-pipelines/IngestPipelineDmDmdiv.test.ts, src/etl/ingest-pipelines/IngestPipelineDmDmdiv.ts, src/etl/ingest-pipelines/IngestPipelineJarde.test.ts, src/etl/ingest-pipelines/IngestPipelineJarde.ts, src/shared/elasticsearch/ElasticsearchService.test.ts, src/shared/elasticsearch/ElasticsearchService.ts, src/shared/elasticsearch/elasticsearchIndexMapping.ts, src/shared/test/helpers/fakeHelper.ts
=> feat: upsert documents in elastic index

src/etl/s3/S3Service.test.ts, src/shared/test/helpers/elasticsearchHelper.ts, vitest.config.ts
=> ECL add stubEnv to tests

.gitignore, README.md, package.json, src/etl/EtlService.test.ts, src/etl/EtlService.ts, src/etl/console.ts, src/shared/elasticsearch/ElasticsearchService.ts
=> ECL add MedDra codes and labels into BDD

docker-compose.yml, src/shared/elasticsearch/ElasticsearchService.ts
=> ECL Refacto code MedDra bulk

src/shared/elasticsearch/ElasticsearchService.test.ts, src/shared/elasticsearch/ElasticsearchService.ts, src/shared/test/helpers/fakeHelper.ts
=> Find just one reference content #126

src/etl/factory/ResearchStudyModelFactory.test.ts, src/etl/factory/ResearchStudyModelFactory.ts, src/shared/models/eclaire/OriginalLanguageContentModel.ts, src/shared/models/eclaire/ReferenceContentsModel.ts
=> feat: save original language content

package.json, src/etl/EtlModule.ts, src/etl/EtlService.test.ts, src/etl/EtlService.ts, src/etl/pipelines/translation/TranslationPipeline.test.ts, src/etl/pipelines/translation/TranslationPipeline.ts, src/shared/test/helpers/translationHelper.ts, src/shared/translation/DeeplModule.ts, src/shared/translation/DeeplService.test.ts, src/shared/translation/DeeplService.ts, yarn.lock
=> feat: add translation service

package.json, src/shared/test/helpers/translationHelper.ts, src/shared/translation/DeeplModule.ts, src/shared/translation/DeeplService.test.ts, src/shared/translation/DeeplService.ts, src/shared/translation/DeeplTranslator.test.ts, src/shared/translation/DeeplTranslator.ts, yarn.lock
=> Change deepl node by node fetch

cron.json, package.json, src/etl/EtlService.test.ts, src/etl/EtlService.ts, src/etl/console.ts, src/etl/pipelines/ingest/IngestPipeline.ts, src/etl/pipelines/ingest/IngestPipelineCtis.test.ts, src/etl/pipelines/ingest/IngestPipelineCtis.ts, src/etl/pipelines/translation/MedDraPipeline.ts, src/etl/pipelines/translation/TranslationPipeline.ts, src/shared/elasticsearch/ElasticsearchService.test.ts, src/shared/elasticsearch/ElasticsearchService.ts, src/shared/models/eclaire/ModelUtils.ts, src/shared/test/snapshots/DailyUpdate.snap.json, src/shared/test/snapshots/DailyUpdateOverTime.snap.json, src/shared/test/snapshots/DailyUpdateSinceYesterday.snap.json, src/shared/test/snapshots/DailyUpdateWithoutNewOnes.snap.json
=> fix daily update

README.md, documentation/post-mortem/20XX-XX-XX - template post-mortem à copier.md
=> doc: ajout procédure rédaction post-mortems + post-mortem de l'issue #170
